Repository esquake/esquake, pull requests merged in 2018-06, with the labels that each got.

#6 현재 위치에서 가까운 곳에 있는 대피소 리스트 리턴하는 기능 구현
  map/index.html
  map/js/map.js
  map/js/shelter.json
Labels: map

#12 지도 위에 마커 생성하는 기능 구현 완료
  map/js/map.js
Labels: map

#15 대피소와 현재 위치 마커 이미지 변경
  map/js/map.js
  map/resource/currentMarkerImage.png
  map/resource/shelterMarkerImage.png
Labels: map

#17 [root page] 메인 페이지 레이아웃 짜기
  src/assets/icon/icMarker.png
  src/assets/icon/icMarker@2x.png
  src/assets/icon/icMarker@3x.png
  src/pages/home/home.html
  src/pages/home/home.ts
  src/pages/search-shelter/search-shelter.html
  src/pages/search-shelter/search-shelter.module.ts
  src/pages/search-shelter/search-shelter.scss
  src/pages/search-shelter/search-shelter.ts
  src/pages/show-shelters/show-shelters.html
  src/pages/show-shelters/show-shelters.module.ts
  src/pages/show-shelters/show-shelters.scss
  src/pages/show-shelters/show-shelters.ts
Labels: front

#39 Server: Firebase에 데이터가 있는지 비교하며 데이터 넣는 기능 구현
  server/crawler.py
Labels: server

#42 Ionic/front
  package-lock.json
  src/app/app.component.ts
  src/assets/icon/5@2x.png
  src/assets/icon/Group 3.png
  src/assets/icon/Group 3@1x.png
  src/assets/icon/Group 3@3x.png
  src/assets/icon/bottomBar.png
  src/assets/icon/icCancel.png
  src/assets/icon/ic_GPS2.png
  src/assets/icon/ic_GPS2@2x.png
  src/assets/icon/ic_eq_history.png
  src/assets/icon/ic_eq_history@2x.png
  src/assets/icon/ic_search.png
  src/assets/icon/ic_survival-book.png
  src/assets/imgs/group.png
  src/assets/imgs/guide10.png
  src/assets/imgs/guide10@2x.png
  src/assets/imgs/guide10@3x.png
  src/assets/imgs/guide11.png
  src/assets/imgs/guide11@2x.png
  src/assets/imgs/guide11@3x.png
  src/assets/imgs/guide9.png
  src/assets/imgs/guide9@2x.png
  src/assets/imgs/guide9@3x.png
  src/pages/eq-behavior/eq-behavior.html
  src/pages/eq-behavior/eq-behavior.module.ts
  src/pages/eq-behavior/eq-behavior.scss
  src/pages/eq-behavior/eq-behavior.ts
  src/pages/eq-history/eq-history.html
  src/pages/eq-history/eq-history.module.ts
  src/pages/eq-history/eq-history.scss
  src/pages/eq-history/eq-history.ts
  src/pages/home/home.html
  src/pages/home/home.ts
  src/pages/list/list.html
  src/pages/list/list.ts
  src/pages/search-shelter/search-shelter.html
  src/pages/search-shelter/search-shelter.ts
  src/pages/show-shelters/show-shelters.html
  src/pages/show-shelters/show-shelters.ts
Labels: front

#44 feat: 반복 주기 3초로 변경
  server/crawler.py
Labels: server

#46 front: 지도 뷰 추가
  map/index.html
  map/js/map.js
  map/js/shelter.json
  package-lock.json
  package.json
  src/app/app.component.ts
  src/app/app.module.ts
  src/assets/imgs/currentMarkerImage.png
  src/assets/imgs/shelterMarkerImage.png
  src/index.html
  src/pages/home/home.html
  src/pages/home/home.ts
  src/pages/search-shelter/search-shelter.html
Labels: front, map

#26 [front] 메인 페이지 레이아웃 짜기
  src/pages/home/home.html
  src/pages/home/home.ts
  src/pages/search-shelter/search-shelter.ts
  src/pages/show-shelters/show-shelters.ts
Labels: front

#48 Front: marker 맵 상에 표현
  config.xml
  src/app/app.module.ts
  src/pages/home/home.html
  src/pages/home/home.ts
Labels: map

#52 Bugfix
  src/app/app.component.ts
  src/pages/home/home.ts
Labels: bug

#53 Feat: json 파일 로드해서 적절한 대피소 출력하는 기능 개발
  config.xml
  package-lock.json
  package.json
  src/app/app.module.ts
  src/assets/shelter.json
  src/pages/eq-behavior/eq-behavior.html
  src/pages/eq-history/eq-history.html
  src/pages/home/home.html
  src/pages/home/home.ts
  src/pages/home/json-typings.d.ts
Labels: front, map

#55 Feat: GPS 버튼 눌리면 타이틀 바뀌는 기능 추가
  src/pages/home/home.html
  src/pages/home/home.ts
Labels: front

#59 Ionic/front
  src/pages/home/home.html
  src/pages/home/home.scss
  src/pages/home/home.ts
  src/pages/search-shelter/search-shelter.ts
  src/pages/show-shelters/show-shelters.html
  src/pages/show-shelters/show-shelters.ts
Labels: front
